"""changes data type for findings description to JSON

Revision ID: 109ef07642cf
Revises: 662f2582f50c
Create Date: 2025-06-23 02:21:18.810478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109ef07642cf'
down_revision = '662f2582f50c'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.alter_column(
            'description',
            existing_type=sa.VARCHAR(length=255),
            type_=sa.JSON(),
            existing_nullable=True,
            postgresql_using="description::json"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
